DayThree.
thanikasomasundaram-t/java-training pull request #1
Opened 2023-03-20 06:10 UTC by thanikasomasundaram-t

Assignment 3 review - > multiThreading

2023-03-20 13:28 UTC, Adheesh-Sirius requested changes

2023-03-20 13:28 UTC, Adheesh-Sirius commented on daythree/src/canthreadruntwotimes/ThreadRepeat.java
> +		one.start();
Can you add your observations as comments at the bottom?

2023-03-20 13:28 UTC, Adheesh-Sirius commented on daythree/src/runningcharacters/RunningCharacters.java
> +				int c = bf.read();
please prefer using elaborated variable names. We'd lose track of what `c` or `bf` mean if this function becomes complex

2023-03-20 13:28 UTC, Adheesh-Sirius commented on daythree/src/printMessage/PrintMessage.java
> +
Here, the goal is to print the string `[------Message------]` with different threads. For instance, thread 1 should print '[', thread 2 should print '------', etc. Can you update the program accordingly?

2023-03-20 13:28 UTC, Adheesh-Sirius commented on daythree/src/oddEven/OddEven.java
> +
Adding comments that explains your approach would be helpful

2023-03-20 14:29 UTC, thanikasomasundaram-t commented on daythree/src/canthreadruntwotimes/ThreadRepeat.java
> +		one.start();
Added the observation.

2023-03-20 14:29 UTC, thanikasomasundaram-t commented on daythree/src/runningcharacters/RunningCharacters.java
> +				int c = bf.read();
Changed to more semantic name.

2023-03-20 14:30 UTC, thanikasomasundaram-t commented on daythree/src/printMessage/PrintMessage.java
> +
tried to move each design message to each thread.

2023-03-20 14:30 UTC, thanikasomasundaram-t commented on daythree/src/oddEven/OddEven.java
> +
Added comments to understand the flow.

2023-03-27 11:07 UTC, Adheesh-Sirius approved these changes

2023-03-28 14:24 UTC, Adheesh-Sirius approved these changes

2023-03-28 14:24 UTC, merged